config/routes.rb
CritterContainer::Application.routes.draw do

  resources :pictures do
    resources :comments do
      member do
        get "upvote"
        get "downvote"
      end 
    end 
    member do
      get "upvote"
      get "downvote"
    end
  end

  devise_for :users
  # devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  root 'pictures#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates_presence_of :comment 
  validates_length_of :comment, 
    :minimum => 8,
    :maximum => 330,
    :short => "Tell us more! (Add some words)"
  
  validates_presence_of :user_id
  validates_presence_of :picture_id

has_many :votes, as: :voteable,
    dependent: :destroy

  belongs_to :user,
    inverse_of: :comments

  belongs_to :picture,
    inverse_of: :comments


def score
    self.votes.inject(0) { |sum, v| sum + v.value }
  end

  def has_user_voted?(user_id)
    self.votes.map { |vote| vote.user_id }.include?(user_id)
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user

  has_many :votes, as: :voteable,
    # inverse_of: :picture,
    dependent: :destroy

  has_many :comments,
    inverse_of: :picture

  acts_as_url :title


  validates_presence_of :user_id
  validates_presence_of :title
  validates_presence_of :image
  mount_uploader :image, ImageUploader

  state_machine initial: :pending do
    event :approve do
      transition pending: :approved
    end

    event :reject do
      transition pending: :rejected
    end
  end 

  def to_param
    url
  end

  def score
    self.votes.inject(0) { |sum, v| sum + v.value }
  end

  def has_user_voted?(user_id)
    self.votes.map { |vote| vote.user_id }.include?(user_id)
  end

  def check_type?(data_type)
    type = data_type.split('/')
    if type[0] != 'image'
      return false
    else
      return true
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :votes,
    inverse_of: :user

  has_many :comments,
    inverse_of: :user

  has_many :pictures,
    inverse_of: :user,
    dependent: :destroy

  validates_presence_of :username
  validates_presence_of :email

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :voteable,
    polymorphic: true #, inverse_of: :vote

  belongs_to :user,
    inverse_of: :votes

  validates :user_id, uniqueness:{ scope: [:voteable_id, :voteable_type] }
  
  validates_inclusion_of :value, in: [-1, 1]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:username]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  
  def index
    @picture = Picture.(params[:picture_id])
    @comment = @picture.comments
  end

  def create
    @picture = Picture.find_by_url!(params[:picture_id])
    @comment = @picture.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to picture_path(@picture),
        notice: "Comment successfully posted"
    else
      redirect_to picture_path(@picture),
        notice: "Your comment was not posted"
    end
  end

  def new
    @comment = Comment.new
    @picture = Picture.find_by_url!(params[:picture_id])
  end

  def upvote
    @picture = Picture.find_by_url!(params[:picture_id])

    record_vote(1)
    redirect_to @picture
  end

  def downvote
    @picture = Picture.find_by_url!(params[:picture_id])
    record_vote(-1)
    redirect_to @picture
  end
  
  def show
  end
  

  private

  
  def comment_params
    params.require(:comment).permit(:comment, :user_id)
  end

  def record_vote(value)
      @comment = Comment.find(params[:id])
      if user_signed_in? 
        vote = @comment.votes.find_or_initialize_by(user_id: current_user.id)
        vote.value = value
        
        vote.save
      end
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_filter :authenticate_user!, only: :edit
  def index
    @comment = Comment.new 

    @q = Picture.search(params[:q])
    @pictures = @q.result(distinct: true)

  end

  def show
    # if params[:id].match(/\d/)  
    #   @picture = Picture.find(params[:id]) 
    #   else
    #     @picture = Picture.find_by_url(params[:id]) 
    #   end
          @picture = Picture.try(:find_by_url, params[:id]) || Picture.try(:find, params[:id])


    # @picture = Picture.find_by_url(params[:id])
    
    @comment = Comment.new 
  end

  def new
    @picture = Picture.new
  end

  def edit
    redirect_to @picture if current_user != @picture.user
  end

  def create
    @picture = Picture.new(picture_params)
    if current_user != nil
      @picture.user_id = current_user.id
      data_type = picture_params[:image].headers.split(' ')[5]
      if @picture.save
          redirect_to picture_path(@picture),
            notice: "What a purr-fect picture!"
      else
        redirect_to new_picture_path, notice: "Error"
      end
    else
      redirect_to new_picture_path, notice: "Please Sign In"
    end
  end
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  def upvote
    record_vote(1)
    set_state
    redirect_to @picture
  end

  def downvote
    record_vote(-1)
    set_state
    redirect_to @picture
  end

  private
    def set_state
      if @picture.score == 2
        @picture.approve
      elsif @picture.score == -2
        @picture.reject
      end
    end

    def set_picture
      @picture = Picture.find_by_url(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:title, :image, :user_id)
    end

    def record_vote(value)      
      
      # if params[:id].match(/\d/)  
      # @picture = Picture.find(params[:id]) 
      # else
      #   @picture = Picture.find_by_url(params[:id]) 
      # end

      @picture = Picture.try(:find_by_url, params[:id]) || Picture.try(:find, params[:id])

      if user_signed_in? 
 
        vote = @picture.votes.find_or_initialize_by(user_id: current_user.id)
        vote.value = value
        vote.save
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/new.html.erb
<%= form_for [@picture, @comment] do |f| %>
  
  <%= f.label :comment %>
  <%= f.text_field :comment %>
  <%= f.submit 'Post comment' %>

<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CritterContainer</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<link href='http://fonts.googleapis.com/css?family=Limelight' rel='stylesheet' type='text/css'>

</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/pictures/new">Upload</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
              <%= current_user.username %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Login <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
              </ul>
          </li> 
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
  <div class='wrapper'>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</body>
</html>

app/views/pictures/_form.html.erb
<div class="jumbotron">
  <div class="container">
  <div class="col-md-8 col-md-offset-2">
    <h1>Upload a picture</h1>
    <%= simple_form_for @picture, :html => {role: "form", :multipart => true} do |f| %>
       <div class="form-group">
        <h2><%= f.input :title, :class => "form-control" %></h2>
          <%= f.file_field :image %>
        </div>
        <%= f.button :submit, :class => "btn btn-primary" %> 
    <% end %>
  </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="jumbotron">
  <div class="container">
  
    <%= search_form_for @q, html: { class: 'form-inline' } do |f| %> 
      
      <%= f.text_field :title_cont, class:'col-md-6 input-lg', placeholder: 'Search for Kittenzz'%>
      <p><%= f.submit 'Search', class:'col-md-1 this_button btn btn-primary' %></p>
    <% end %>
    <div class='cat_icon'></div>
    <div style='clear:both;'></div>
  </div>
</div>



<% @pictures.each_with_index do |picture, index| %>
  <% if index.even? %>
    <div style='float:left'class="cont col-sm-8 col-md-8 col-xs-8">
      <div class="thumbnail">
          <a href="/pictures/<%=picture.id%>">
            <img href='<%= picture_path(picture)%>' src=<%= picture.image.to_s %>>  
            </a>
        <div class="caption">
          <h3><%= picture.title %></h3>
            <p>
              
            <% if user_signed_in? %>
              
              <a class= 'btn btn-primary' href='#' 
              onclick='submit_pic_upvote(<%= picture.id %>)' id='upvote'>▲</a>
              <a class= 'btn btn-primary' href='#' 
              onclick='submit_pic_downvote(<%= picture.id %>)' id='downvote'>▼</a>

              <a style='float:right'class='btn btn-primary' onclick='comment_toggle(<%=picture.id%>);'> Comment </a>
                <div class='commentForm' id="comment_<%=picture.id%>">
                <%= form_for [picture, @comment] do |f| %>
                
                  <%= f.text_field :comment %>
                  <%= f.submit 'Post comment', class:'btn btn-primary' %>
                <%- end -%>
              </div>
            <%- end -%>
            </p>
        </div>
      </div>
    </div>
    <div class="cont col-sm-4 col-md-4 col-xs-4">
      <h2> Comments </h2>
      <ul class="list-group">


    <% picture.comments.each do |comment| %>
       <li class="list-group-item">
        <p style='float:left'>
         <%= comment.comment %>
        </p>
        <div class='float_right'>      
          <%= comment.user.username %>
          <%= link_to '▲', upvote_picture_comment_path(picture, comment.id),
          id: 'comment_upvote_#{comment.id}' %>
          <%= link_to '▼', downvote_picture_comment_path(picture, comment.id), id: 'comment_downvote_#{comment.id}'%>
        </div>
        <div style='clear:both'></div>
        </li>
      
    <%- end -%>
    </ul>
    </div>
<% else %>
 <div style='float:left'class="cont col-sm-4 col-md-4 col-xs-4">
  <h2> Comments </h2>
   <ul class="list-group">
    <% picture.comments.each do |comment| %>
        <li class="list-group-item">
          <p style='float:left'>
            <%= comment.comment %>
          </p>

          <div class='float_right'>      
            <%= comment.user.username %>
            <%= link_to '▲', upvote_picture_comment_path(picture, comment.id),
            id: 'comment_upvote_#{comment.id}' %>
            <%= link_to '▼', downvote_picture_comment_path(picture, comment.id), id: 'comment_downvote_#{comment.id}'%>
          </div>
        <div style='clear:both'></div>
        </li>
        
    <%- end -%>
    </ul>
    </div>
  <div style='float:right;' class=" cont col-sm-8 col-md-8 col-xs-8">  
      <div class="thumbnail">
          <a href="/pictures/<%=picture.id%>">
            <img href='<%= picture_path(picture)%>' src=<%= picture.image.to_s %>>
            </a>  
        <div class="caption">
          <h3><%= picture.title %></h3>
            <p>
         <!--    <%= link_to '▲', upvote_picture_path(picture), class:'btn btn-primary', id: 'upvote' %>
            <%= link_to '▼', downvote_picture_path(picture), class:'btn btn-default', id: 'downvote' %> -->
             <a class= 'btn btn-primary' href='#' 
            onclick='submit_pic_upvote(<%= picture.id %>)' id='upvote'>▲</a>
            <a class= 'btn btn-primary' href='#' 
            onclick='submit_pic_downvote(<%= picture.id %>)' id='downvote'>▼</a>
            <% if user_signed_in? %>
              <a style='float:right'class='btn btn-primary' onclick='comment_toggle(<%=picture.id%>);'> Comment </a>
                <div class='commentForm' id="comment_<%=picture.id%>">
                <%= form_for [picture, @comment] do |f| %>
                  <%= f.text_field :comment %>


                   <%= f.submit 'Post comment', class:'btn btn-primary' %>

                <%- end -%>
              </div>
            <%- end -%>
            </p>
        </div>
      </div>
    </div>
   

  <% end %>

<div style='clear:both'></div>
<div class='border'></div>

<% end %>

app/views/pictures/new.html.erb
<%= render 'pictures/form', pictures: @pictures %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
    <div class="container">
      <h1>   <%= @picture.title %>
      <%= link_to '▲', upvote_picture_path(@picture), id: 'upvote' %>
       <%= link_to '▼', downvote_picture_path(@picture), id: 'downvote' %>
      </h1>
      <p>  
        <%= link_to 'Edit', edit_picture_path(@picture), :class => "btn btn-primary btn-sm" %> 
        <%= link_to 'Back', pictures_path, :class => "btn btn-primary btn-sm" %><br>
      </p>
    </div>
</div>
  
  <p><strong>What a purr-fect picture!</strong></p>
<div class="container">
  <div class='col-md-8'>
    <img src=<%= @picture.image.to_s %>>
    <% if user_signed_in? %>
        <%= form_for [@picture, @comment] do |f| %>

          <br><%= f.label :comment %><br>
          <%= f.text_field :comment %><br><br>
          <%= f.submit 'Post comment', :class => "btn btn-primary" %>

        <%- end -%>
    </div>
    <% else %>
      <a href="<%= new_user_session_path %>">Sign In To Comment</a>
    <%- end -%>

<% @picture.comments.each do |comment| %>
  <div class='comment'><br>
  <%= comment.comment %>
  
  <%= link_to '▲', upvote_picture_comment_path(@picture, comment.id), id: 'comment_upvote_#{comment.id}' %>
  <%= link_to '▼', downvote_picture_comment_path(@picture, comment.id), id: 'comment_downvote_#{comment.id}' %>
  </div>

<%- end -%>

</div>